export enum COLLECTION_NAMES {
    NONCE = 'nonces',
    USER = 'users',
    ROLE = 'roles',
    PERMISSION = 'permissions',
    FILE = 'files',
    METADATA = 'metadata',
    CATEGORIES = 'categories',
    POST = 'posts',
    AUDIT = 'audits',
    APP = 'apps',
    REVIEW_RATING = 'review-ratings',
    ADVERTISER = 'advertisers',
    USER_APP_HISTORY = 'userAppHistories',
    TELEGRAM_BOT = 'telegramBots',
    TAG = 'tags',
    TAG_APP = 'tagApps',
    USER_TRANSACTION = 'userTransactions',
    NOTIFICATION = 'notifications',
    FORM_BUILDER = 'formBuilders',
}

export const PERMISSIONS = {
    USER: {
        index: 'admin.users.index',
        create: 'admin.users.create',
        edit: 'admin.users.edit',
        destroy: 'admin.users.destroy',
    },
    ROLE: {
        index: 'admin.roles.index',
        create: 'admin.roles.create',
        edit: 'admin.roles.edit',
        destroy: 'admin.roles.destroy',
    },
    FILE: {
        index: 'admin.files.index',
        create: 'admin.files.create',
        edit: 'admin.files.edit',
        destroy: 'admin.files.destroy',
    },
    CATEGORIES: {
        index: 'admin.categories.###.index',
        create: 'admin.categories.###.create',
        edit: 'admin.categories.###.edit',
        destroy: 'admin.categories.###.destroy',
    },
    POST: {
        index: 'admin.posts.###.index',
        create: 'admin.posts.###.create',
        edit: 'admin.posts.###.edit',
        destroy: 'admin.posts.###.destroy',
    },
    AUDIT: {
        index: 'admin.audits.index',
    },
    PERMISSION: {
        index: 'admin.permissions.index',
    },
    APP: {
        index: 'admin.apps.index',
        create: 'admin.apps.create',
        edit: 'admin.apps.edit',
        destroy: 'admin.apps.destroy',
    },
    REVIEW: {
        index: 'admin.reviews.index',
        create: 'admin.reviews.create',
        edit: 'admin.reviews.edit',
        destroy: 'admin.reviews.destroy',
    },
    ADVERTISER: {
        index: 'admin.advertisers.index',
        create: 'admin.advertisers.create',
        edit: 'admin.advertisers.edit',
        destroy: 'admin.advertisers.destroy',
    },
    REDIS: {
        index: 'admin.redis.destroy',
    },
    TELEGRAM_BOT: {
        index: 'admin.telegram-bots.index',
        create: 'admin.telegram-bots.create',
        edit: 'admin.telegram-bots.edit',
        destroy: 'admin.telegram-bots.destroy',
    },
    TAG: {
        index: 'admin.tags.index',
        create: 'admin.tags.create',
        edit: 'admin.tags.edit',
        destroy: 'admin.tags.destroy',
    },
    USER_TRANSACTION: {
        index: 'admin.user-transactions.index',
    },
    NOTIFICATION: {
        index: 'admin.notifications.index',
        create: 'admin.notifications.create',
        edit: 'admin.notifications.edit',
        destroy: 'admin.notifications.destroy',
    },
    FORM_BUILDER: {
        index: 'admin.form-builders.index',
        destroy: 'admin.form-builders.destroy',
    },
};

export const PERMISSIONS_FRONT = {
    USER: {
        index: 'front.users.index',
        create: 'front.users.create',
        edit: 'front.users.edit',
        destroy: 'front.users.destroy',
    },
    CATEGORIES: {
        index: 'front.categories.###.index',
        create: 'front.categories.###.create',
        edit: 'front.categories.###.edit',
        destroy: 'front.categories.###.destroy',
    },
    POST: {
        index: 'front.posts.###.index',
        create: 'front.posts.###.create',
        edit: 'front.posts.###.edit',
        destroy: 'front.posts.###.destroy',
    },
    FILE: {
        index: 'front.files.index',
        create: 'front.files.create',
        edit: 'front.files.edit',
        destroy: 'front.files.destroy',
    },
    APP: {
        index: 'front.apps.index',
        create: 'front.apps.create',
        edit: 'front.apps.edit',
        destroy: 'front.apps.destroy',
        submit: 'front.apps.submit',
    },
    REVIEW: {
        index: 'front.reviews.index',
        create: 'front.reviews.create',
        edit: 'front.reviews.edit',
        destroy: 'front.reviews.destroy',
    },
    NOTIFICATION: {
        index: 'front.notifications.index',
        edit: 'front.notifications.edit',
        destroy: 'front.notifications.destroy',
    },
    FORM_BUILDER: {
        create: 'front.form-builder.create',
    },
};
export enum CountryCode {
    GLOBAL = 'GLOBAL',
    AF = 'AF',
    AX = 'AX',
    AL = 'AL',
    DZ = 'DZ',
    AS = 'AS',
    AD = 'AD',
    AO = 'AO',
    AI = 'AI',
    AQ = 'AQ',
    AG = 'AG',
    AR = 'AR',
    AM = 'AM',
    AW = 'AW',
    AU = 'AU',
    AT = 'AT',
    AZ = 'AZ',
    BS = 'BS',
    BH = 'BH',
    BD = 'BD',
    BB = 'BB',
    BY = 'BY',
    BE = 'BE',
    BZ = 'BZ',
    BJ = 'BJ',
    BM = 'BM',
    BT = 'BT',
    BO = 'BO',
    BA = 'BA',
    BW = 'BW',
    BV = 'BV',
    BR = 'BR',
    IO = 'IO',
    BN = 'BN',
    BG = 'BG',
    BF = 'BF',
    BI = 'BI',
    KH = 'KH',
    CM = 'CM',
    CA = 'CA',
    CV = 'CV',
    KY = 'KY',
    CF = 'CF',
    TD = 'TD',
    CL = 'CL',
    CN = 'CN',
    CX = 'CX',
    CC = 'CC',
    CO = 'CO',
    KM = 'KM',
    CG = 'CG',
    CD = 'CD',
    CK = 'CK',
    CR = 'CR',
    CI = 'CI',
    HR = 'HR',
    CU = 'CU',
    CY = 'CY',
    CZ = 'CZ',
    DK = 'DK',
    DJ = 'DJ',
    DM = 'DM',
    DO = 'DO',
    EC = 'EC',
    EG = 'EG',
    SV = 'SV',
    GQ = 'GQ',
    ER = 'ER',
    EE = 'EE',
    ET = 'ET',
    FK = 'FK',
    FO = 'FO',
    FJ = 'FJ',
    FI = 'FI',
    FR = 'FR',
    GF = 'GF',
    PF = 'PF',
    TF = 'TF',
    GA = 'GA',
    GM = 'GM',
    GE = 'GE',
    DE = 'DE',
    GH = 'GH',
    GI = 'GI',
    GR = 'GR',
    GL = 'GL',
    GD = 'GD',
    GP = 'GP',
    GU = 'GU',
    GT = 'GT',
    GG = 'GG',
    GN = 'GN',
    GW = 'GW',
    GY = 'GY',
    HT = 'HT',
    HM = 'HM',
    VA = 'VA',
    HN = 'HN',
    HK = 'HK',
    HU = 'HU',
    IS = 'IS',
    IN = 'IN',
    ID = 'ID',
    IR = 'IR',
    IQ = 'IQ',
    IE = 'IE',
    IM = 'IM',
    IL = 'IL',
    IT = 'IT',
    JM = 'JM',
    JP = 'JP',
    JE = 'JE',
    JO = 'JO',
    KZ = 'KZ',
    KE = 'KE',
    KI = 'KI',
    KR = 'KR',
    KP = 'KP',
    KW = 'KW',
    KG = 'KG',
    LA = 'LA',
    LV = 'LV',
    LB = 'LB',
    LS = 'LS',
    LR = 'LR',
    LY = 'LY',
    LI = 'LI',
    LT = 'LT',
    LU = 'LU',
    MO = 'MO',
    MK = 'MK',
    MG = 'MG',
    MW = 'MW',
    MY = 'MY',
    MV = 'MV',
    ML = 'ML',
    MT = 'MT',
    MH = 'MH',
    MQ = 'MQ',
    MR = 'MR',
    MU = 'MU',
    YT = 'YT',
    MX = 'MX',
    FM = 'FM',
    MD = 'MD',
    MC = 'MC',
    MN = 'MN',
    ME = 'ME',
    MS = 'MS',
    MA = 'MA',
    MZ = 'MZ',
    MM = 'MM',
    NA = 'NA',
    NR = 'NR',
    NP = 'NP',
    NL = 'NL',
    AN = 'AN',
    NC = 'NC',
    NZ = 'NZ',
    NI = 'NI',
    NE = 'NE',
    NG = 'NG',
    NU = 'NU',
    NF = 'NF',
    MP = 'MP',
    NO = 'NO',
    OM = 'OM',
    PK = 'PK',
    PW = 'PW',
    PS = 'PS',
    PA = 'PA',
    PG = 'PG',
    PY = 'PY',
    PE = 'PE',
    PH = 'PH',
    PN = 'PN',
    PL = 'PL',
    PT = 'PT',
    PR = 'PR',
    QA = 'QA',
    RE = 'RE',
    RO = 'RO',
    RU = 'RU',
    RW = 'RW',
    BL = 'BL',
    SH = 'SH',
    KN = 'KN',
    LC = 'LC',
    MF = 'MF',
    PM = 'PM',
    VC = 'VC',
    WS = 'WS',
    SM = 'SM',
    ST = 'ST',
    SA = 'SA',
    SN = 'SN',
    RS = 'RS',
    SC = 'SC',
    SL = 'SL',
    SG = 'SG',
    SK = 'SK',
    SI = 'SI',
    SB = 'SB',
    SO = 'SO',
    ZA = 'ZA',
    GS = 'GS',
    ES = 'ES',
    LK = 'LK',
    SD = 'SD',
    SR = 'SR',
    SJ = 'SJ',
    SZ = 'SZ',
    SE = 'SE',
    CH = 'CH',
    SY = 'SY',
    TW = 'TW',
    TJ = 'TJ',
    TZ = 'TZ',
    TH = 'TH',
    TL = 'TL',
    TG = 'TG',
    TK = 'TK',
    TO = 'TO',
    TT = 'TT',
    TN = 'TN',
    TR = 'TR',
    TM = 'TM',
    TC = 'TC',
    TV = 'TV',
    UG = 'UG',
    UA = 'UA',
    AE = 'AE',
    GB = 'GB',
    US = 'US',
    UM = 'UM',
    UY = 'UY',
    UZ = 'UZ',
    VU = 'VU',
    VE = 'VE',
    VN = 'VN',
    VG = 'VG',
    VI = 'VI',
    WF = 'WF',
    EH = 'EH',
    YE = 'YE',
    ZM = 'ZM',
    ZW = 'ZW',
}
