export const EVENT_NAME = {
    MISSION_UPDATE: 'MISSION_UPDATE',
    POINT_UPDATE: 'POINT_UPDATE',
    NEW_REVIEW_RATING: 'NEW_REVIEW_RATING',
    GET_LIMIT_ADD_POINT_FOR_USER: 'GET_LIMIT_ADD_POINT_FOR_USER',
    NEW_NOTIFICATION: 'NEW_NOTIFICATION',
    COUNT_NOTIFICATION_UNREAD: 'COUNT_NOTIFICATION_UNREAD',
};
