export enum UserNotificationStatus {
    READ = 'READ',
    UNREAD = 'UNREAD',
}

export const NOTIFICATION_EVENT = {
    SEND_FOR_USERS: 'SEND_FOR_USERS',
    SEND_FOR_ADMIN_TO_APPROVING_COMMENT: 'SEND_FOR_ADMIN_TO_APPROVING_COMMENT',
};
