export enum MetadataType {
    AMOUNT_REWARD_USER_OPEN_APP = 'AMOUNT_REWARD_USER_OPEN_APP',
    AMOUNT_REWARD_USER_COMMENT_APP = 'AMOUNT_REWARD_USER_COMMENT_APP',
    AMOUNT_REWARD_USER_SHARE_APP = 'AMOUNT_REWARD_USER_SHARE_APP',
    AMOUNT_REWARD_USER_GLOBAL = 'AMOUNT_REWARD_USER_GLOBAL',
    AMOUNT_REWARD_REFERRAL = 'AMOUNT_REFERRAL_REWARD',
}
